[tool.poetry]
name = "swaron-email-api"
version = "0.1.0"
description = ""
authors = ["pedro_gonsalves@hotmail.com"]

[tool.poetry.dependencies]
python = "^3.10"
anyio="3.6.2"
fastapi="0.95.1"
greenlet="2.0.2"
idna="3.4"
psycopg2="2.9.6"
pydantic="1.10.7"
python-dotenv="1.0.0"
sniffio="1.3.0"
SQLAlchemy="1.4.46"
starlette="0.26.1"
typing_extensions="4.5.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]

[tool.poetry.extras]